### ISSUE TITLE
Recipe MVP Checklist

### ISSUE THREAD

**Issue by jmcbgaston** [jmcbgaston/allmyverybestrecipes#5]
# Recipes

## Functionality

- [ ] Homepage displays recipes index
- [ ] Profile displays index of your own recipes
- [ ] Can create a recipe
- [ ] Can edit only your own recipe
- [ ] Can delete only your own recipe
- [ ] Can only delete on edit recipe form
- [ ] Recipe show page has link back to homepage
- [ ] Page refresh persists content
- [ ] Recipe form displays errors

## Style

- [ ] Create/Edit recipe forms are styled
- [ ] Your Profile's recipe index is styled
- [ ] Recipe show page is styled
